{
  pkgs,
  config,
  ...
}:

let
  colors = config.lib.stylix.colors; # base16.nix scheme attrs from stylix.base16Scheme
in
{
  home.packages = with pkgs; [
    # LSP servers & tools — the neovim binary itself is installed by HM's
    # programs.neovim (wrapped with plugins), so it no longer lives here
    lua-language-server
    nixd
    alejandra
    stylua
    rust-analyzer
    lldb # DAP debugger for rustaceanvim (:RustDebuggables) — provides lldb-dap
    tailwindcss-language-server
    typescript-language-server
    lazygit
    nodejs

    # Formatters (used by conform.nvim)
    prettierd

    # Treesitter auto_install deps (CLI + C compiler for parser builds)
    tree-sitter
    gcc

    # System clipboard providers (Wayland + X11 fallback)
    wl-clipboard
    xclip
  ];

  home.shellAliases = {
    vi = "nvim";
    vim = "nvim";
    v = "nvim";
  };

  programs.neovim = {
    enable = true;
    # HM wraps this base itself (wrapNeovimUnstable), installing the result as
    # finalPackage. Must be the unwrapped binary: wrapping pkgs.neovim (the
    # default wrapper) double-wraps, and on current nixpkgs that breaks the
    # wrapper build (its lndir copies pkgs.neovim's read-only root rplugin.vim,
    # which the wrapper's postBuild touch then can't write). Same 0.12.x binary.
    package = pkgs.neovim-unwrapped;
    initLua = builtins.readFile ./init.lua; # HM master option (extraLuaConfig renamed)
  };

  stylix.targets.neovim = {
    enable = true;
    # Palette setup lives in colors/stylix.lua (needed for a named :colorscheme and the
    # ColorScheme-autocmd reapplication of mini.* overrides). Disabling colors.enable
    # suppresses Stylix's duplicate require('mini.base16').setup() in the plugin config,
    # which would run AFTER init.lua (HM plugin config is mkAfter) and clobber those
    # overrides. The plugin entry (mini-nvim + transparency) is gated on cfg.enable only.
    colors.enable = false;
    transparentBackground = {
      main = true;      # Normal/NonText bg NONE — matches old matugen.lua
      signColumn = true; # SignColumn bg NONE — matches old matugen.lua
      numberLine = true; # LineNr bg NONE — matches old matugen.lua
    };
  };

  # Named colorscheme from stylix.base16Scheme (themeFile when useThemeFile=true,
  # generator scheme otherwise — single source of truth). mini.base16 colorscheme pattern:
  # setup(palette) then set g.colors_name. Symlink target changes on every nh switch when
  # the palette changes; init.lua FS-watches this path and re-sources :colorscheme stylix.
  xdg.configFile."nvim/colors/stylix.lua".text = ''
    -- Generated by home-manager from stylix.base16Scheme. Do not edit.
    require('mini.base16').setup({
      palette = {
        base00 = '${colors.withHashtag.base00}',
        base01 = '${colors.withHashtag.base01}',
        base02 = '${colors.withHashtag.base02}',
        base03 = '${colors.withHashtag.base03}',
        base04 = '${colors.withHashtag.base04}',
        base05 = '${colors.withHashtag.base05}',
        base06 = '${colors.withHashtag.base06}',
        base07 = '${colors.withHashtag.base07}',
        base08 = '${colors.withHashtag.base08}',
        base09 = '${colors.withHashtag.base09}',
        base0A = '${colors.withHashtag.base0A}',
        base0B = '${colors.withHashtag.base0B}',
        base0C = '${colors.withHashtag.base0C}',
        base0D = '${colors.withHashtag.base0D}',
        base0E = '${colors.withHashtag.base0E}',
        base0F = '${colors.withHashtag.base0F}',
      },
    })
    vim.g.colors_name = 'stylix'
    vim.opt.background = '${config.stylix.polarity}'
  '';
}
