[audio]
enable_overdrive = true
enable_sounds = true
notification_sound = ""
sound_volume = 0.5
volume_change_sound = ""

[backdrop]
blur_intensity = 0.5
enabled = false
tint_intensity = 0.30000001192092896

[bar]
order = [ "default" ]

    [bar.default]
    auto_hide = false
    background_opacity = 0.5
    border = "outline"
    border_width = 0.0
    capsule = false
    capsule_fill = "surface_variant"
    capsule_group = []
    capsule_opacity = 1.0
    capsule_padding = 6.0
    center = [ "media", "notifications" ]
    color = "on_surface"
    contact_shadow = false
    enabled = true
    end = [ "battery_1", "network", "bluetooth", "battery_2", "volume", "tray" ]
    font_weight = 400
    layer = "top"
    margin_edge = 4
    margin_ends = 4
    padding = 14
    panel_overlap = 1
    position = "top"
    radius = 12
    radius_bottom_left = 12
    radius_bottom_right = 12
    radius_top_left = 12
    radius_top_right = 12
    reserve_space = true
    scale = 1.0
    shadow = true
    start = [ "clock" ]
    thickness = 34
    widget_spacing = 12

[battery]
warning_threshold = 20

[brightness]
enable_ddcutil = false
ignore_mmids = []

[calendar]
enabled = false
refresh_minutes = 15

[control_center]
sidebar = "compact"
sidebar_section = "compact"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "power_profile"

[desktop_widgets]
enabled = true
schema_version = 2

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

[dock]
active_monitor_only = true
active_opacity = 1.0
active_scale = 1.0
auto_hide = true
background_opacity = 0.87999999523162842
cross_axis_padding = 8
enabled = true
icon_size = 24
inactive_opacity = 0.85000002384185791
inactive_scale = 0.85000002384185791
item_spacing = 6
launcher_icon = "grid-dots"
launcher_position = "start"
magnification = true
magnification_scale = 1.4500000476837158
main_axis_padding = 16
margin_edge = 8
margin_ends = 0
monitors = []
pinned = []
position = "bottom"
radius = 16
radius_bottom_left = 16
radius_bottom_right = 16
radius_top_left = 16
radius_top_right = 16
reserve_space = false
shadow = true
show_dots = false
show_instance_count = true
show_running = true

[hooks]
battery_charging = []
battery_discharging = []
battery_percentage_changed = []
battery_plugged = []
bluetooth_disabled = []
bluetooth_enabled = []
colors_changed = []
logging_out = []
power_profile_changed = []
rebooting = []
session_locked = []
session_unlocked = []
shutting_down = []
started = []
theme_mode_changed = []
wallpaper_changed = []
wifi_disabled = []
wifi_enabled = []

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 2.0

    [idle.behavior.lock]
    action = "lock"
    command = ""
    enabled = true
    resume_command = ""
    timeout = 600

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    command = ""
    enabled = false
    resume_command = ""
    timeout = 900

    [idle.behavior.screen-off]
    action = "screen_off"
    command = ""
    enabled = false
    resume_command = ""
    timeout = 660

[keybinds]
cancel = [ "Escape" ]
down = [ "Down" ]
left = [ "Left" ]
right = [ "Right" ]
up = [ "Up" ]
validate = [ "Return", "KP_Enter" ]

[location]
address = ""
auto_locate = true
sunrise = ""
sunset = ""

[lockscreen]
blur_intensity = 0.5
blurred_desktop = true
monitors = []
tint_intensity = 0.30000001192092896
wallpaper = ""

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005"
]

    [lockscreen_widgets.grid]
    cell_size = 64
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    enabled = true
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    enabled = true
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 464.0
    box_width = 496.0
    cx = 960.0
    cy = 540.0
    enabled = true
    output = "HDMI-A-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        bar_width = 0.69999999999999996
        bloom_intensity = 0.30000000000000004
        fade_when_idle = true
        inner_diameter = 0.25
        ring_opacity = 0.60000000000000009
        rotation_speed = 0.30000000000000004
        sensitivity = 2.4000000000000004
        visualization_mode = "bars_rings"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 320.0
    box_width = 256.0
    cx = 1760.0
    cy = 188.0
    enabled = true
    output = "HDMI-A-1"
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.40000000000000002
        background_padding = 0.0
        background_radius = 9.0
        color = "primary"
        hide_when_no_media = true
        layout = "vertical"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 128.0
    box_width = 512.0
    cx = 960.0
    cy = 220.0
    enabled = true
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = true
        background_opacity = 0.75
        background_padding = 4.0
        background_radius = 9.0
        circle = true
        clock_style = "digital"
        format = "{:%Y/%m/%d}"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 128.0
    box_width = 256.0
    cx = 960.0
    cy = 372.0
    enabled = true
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        shadow = false

[nightlight]
enabled = false
force = false
temperature_day = 6500
temperature_night = 4000

[notification]
allowed_urgencies = []
background_opacity = 0.97000002861022949
blacklist = []
blacklist_allow_critical = true
collapse_on_dismiss = true
enable_daemon = true
layer = "top"
monitors = []
offset_x = 20
offset_y = 8
position = "top_right"
scale = 1.0
show_actions = true
show_app_name = true

[osd]
background_opacity = 0.97000002861022949
monitors = []
offset_x = 20
offset_y = 8
orientation = "vertical"
position = "bottom_right"
scale = 1.0

    [osd.kinds]
    bluetooth = true
    brightness = true
    caffeine = true
    dnd = true
    keyboard_layout = true
    lock_keys = true
    power_profile = true
    volume = true
    volume_input = true
    volume_output = true
    wifi = true

[shell]
app_icon_colorize = false
avatar_path = ""
clipboard_auto_paste = "auto"
clipboard_confirm_clear_history = true
clipboard_enabled = true
clipboard_history_max_entries = 50
clipboard_image_action_command = ""
corner_radius_scale = 1.4500000476837158
date_format = "%A, %x"
disable_mipmaps = false
font_family = "sans-serif"
launch_apps_as_systemd_services = false
middle_click_opens_widget_settings = true
niri_overview_type_to_launch_enabled = false
offline_mode = false
password_style = "random"
polkit_agent = true
screen_time_enabled = false
settings_show_advanced = true
setup_wizard_enabled = true
shared_gl_context = true
show_location = true
telemetry_enabled = false
time_format = "{:%H:%M}"
ui_scale = 0.85000002384185791

    [shell.animation]
    enabled = true
    speed = 1.0

    [shell.mpris]
    blacklist = []

    [shell.panel]
    borders = true
    clipboard_placement = "centered"
    control_center_placement = "attached"
    launcher_categories = true
    launcher_compact = true
    launcher_placement = "centered"
    launcher_show_icons = true
    open_near_click_clipboard = false
    open_near_click_control_center = true
    open_near_click_launcher = false
    open_near_click_session = false
    open_near_click_wallpaper = false
    session_placement = "attached"
    shadow = true
    transparency_mode = "glass"
    wallpaper_placement = "attached"

    [shell.screen_corners]
    enabled = true
    size = 16

    [shell.screenshot]
    copy_to_clipboard = true
    directory = ""
    filename_pattern = ""
    freeze_screen = true
    pipe_command = ""
    pipe_to_command = false
    save_to_file = true

    [[shell.session.actions]]
    action = "lock"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "5"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.55000001192092896
    direction = "down"

[system.monitor]
cpu_poll_seconds = 2.0
cpu_temp_activity_threshold = 60.0
cpu_temp_critical_threshold = 85.0
cpu_usage_activity_threshold = 50.0
cpu_usage_critical_threshold = 90.0
disk_pct_activity_threshold = 80.0
disk_pct_critical_threshold = 95.0
disk_poll_seconds = 10.0
enabled = true
gpu_poll_seconds = 0.0
gpu_temp_activity_threshold = 60.0
gpu_temp_critical_threshold = 85.0
gpu_usage_activity_threshold = 50.0
gpu_usage_critical_threshold = 95.0
gpu_vram_activity_threshold = 50.0
gpu_vram_critical_threshold = 90.0
memory_poll_seconds = 2.0
net_rx_activity_threshold = 1.0
net_rx_critical_threshold = 50.0
net_tx_activity_threshold = 1.0
net_tx_critical_threshold = 50.0
network_poll_seconds = 3.0
ram_pct_activity_threshold = 60.0
ram_pct_critical_threshold = 90.0
swap_pct_activity_threshold = 20.0
swap_pct_critical_threshold = 80.0

[theme]
builtin = "Rosé Pine"
community_palette = "Rose Pine Moon"
custom_palette = "stylix"
mode = "light"
source = "custom"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = []
    community_ids = []
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/felipe/nix-config/assets/wallpapers"
directory_dark = ""
directory_light = ""
edge_smoothness = 0.30000001192092896
enabled = false
fill_color = ""
fill_mode = "crop"
per_monitor_directories = false
transition = [ "fade", "wipe", "disc", "stripes", "zoom", "honeycomb" ]
transition_duration = 1500.0
transition_on_startup = false

    [wallpaper.automation]
    enabled = false
    interval_seconds = 1800
    order = "random"
    recursive = true

[weather]
effects = true
enabled = true
refresh_minutes = 30
unit = "metric"

[widget.active_window]
icon_size = 14.0
max_length = 260.0
min_length = 80.0
title_scroll = "none"
type = "active_window"

[widget.battery]
device = "/org/freedesktop/UPower/devices/headset_dev_F5_5B_D3_3D_EA_9E"
display_mode = "graphic"
show_label = false
type = "battery"

[widget.battery_1]
device = "/org/freedesktop/UPower/devices/battery_BAT0"
display_mode = "graphic"
hide_when_full = true
show_label = false
type = "battery"

[widget.battery_2]
device = "/org/freedesktop/UPower/devices/headset_dev_F5_5B_D3_3D_EA_9E"
display_mode = "graphic"
show_label = false
type = "battery"

[widget.bluetooth]
hide_when_no_connected_device = false
type = "bluetooth"

[widget.bongocat]
audio_spectrum = true
rave_mode = true
script = "scripts/bongocat.lua"
tappy_mode = true
type = "scripted"
use_mpris_filter = true

[widget.clock]
format = "{:%Y/%m/%d %H:%M}"
type = "clock"

[widget.cpu]
stat = "cpu_usage"
type = "sysmon"

[widget.date]
format = "{:%a %d %b}"
type = "clock"

[widget.input_volume]
device = "input"
type = "volume"

[widget.keyboard_layout]
cycle_command = ""
hide_when_single_layout = false
type = "keyboard_layout"

[widget.lock_keys]
display = "short"
hide_when_off = false
show_caps_lock = true
show_num_lock = true
show_scroll_lock = false
type = "lock_keys"

[widget.media]
art_size = 16.0
hide_when_no_media = true
max_length = 500
min_length = 80.0
title_scroll = "always"
type = "media"

[widget.network]
show_label = false
type = "network"

[widget.network_rx]
stat = "net_rx"
type = "sysmon"

[widget.network_tx]
stat = "net_tx"
type = "sysmon"

[widget.notifications]
hide_when_no_unread = true
type = "notifications"

[widget.output_volume]
device = "output"
type = "volume"

[widget.ram]
stat = "ram_used"
type = "sysmon"

[widget.spacer]
type = "spacer"

[widget.temp]
stat = "cpu_temp"
type = "sysmon"

[widget.tray]
drawer = true
type = "tray"

[widget.volume]
show_label = false
type = "volume"

[widget.workspaces]
display = "none"
hide_when_empty = true
labels_only_when_occupied = true
type = "workspaces"
