# NixOS System Configuration
# This file defines the system-wide configuration for NixOS.
# For detailed documentation, see:
# - configuration.nix(5) man page
# - NixOS manual (run 'nixos-help')

{
  inputs,
  config,
  pkgs,
  ...
}:

{
  # ============================================================================
  # IMPORTS
  # ============================================================================
  imports = [
    # Hardware configuration generated by nixos-generate-config
    ./hardware-configuration.nix

    # Home Manager integration
    inputs.home-manager.nixosModules.home-manager

    # System modules
    ./packages.nix
    ./stylix.nix
    ./gtk.nix
    ./upower.nix
    ./docker.nix
    ./flutter.nix
    ./jellyfin.nix
    # ./subsonic.nix
    ./nh.nix
    ./networkmanager.nix
    ./noctalia.nix
    ./steam.nix
    ./substituters.nix
    ./thunderbird.nix
    ./xautolock.nix
    ./vial.nix
    ./niri.nix
    ./wine.nix
    ./nicotine-plus.nix
    # ./mysql.nix
  ];

  # ============================================================================
  # HOME MANAGER
  # ============================================================================
  home-manager = {
    extraSpecialArgs = { inherit inputs; };
    backupFileExtension = "hm-backup"; # Prevents Stylix conflicts
    users.felipe = import ../home-manager/home.nix;
  };

  # ============================================================================
  # BOOT & LOADER
  # ============================================================================
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  # ============================================================================
  # NETWORKING
  # ============================================================================
  networking = {
    hostName = "nixos";
    networkmanager.enable = true;

    # Wireless support (uncomment if needed)
    # wireless.enable = true;

    # Proxy configuration (uncomment and configure if needed)
    # proxy.default = "http://user:password@proxy:port/";
    # proxy.noProxy = "127.0.0.1,localhost,internal.domain";
  };

  # ============================================================================
  # LOCALIZATION
  # ============================================================================
  time.timeZone = "America/Santarem";

  i18n = {
    defaultLocale = "en_US.UTF-8";

    extraLocaleSettings = {
      LC_ADDRESS = "pt_BR.UTF-8";
      LC_IDENTIFICATION = "pt_BR.UTF-8";
      LC_MEASUREMENT = "pt_BR.UTF-8";
      LC_MONETARY = "pt_BR.UTF-8";
      LC_NAME = "pt_BR.UTF-8";
      LC_NUMERIC = "pt_BR.UTF-8";
      LC_PAPER = "pt_BR.UTF-8";
      LC_TELEPHONE = "pt_BR.UTF-8";
      LC_TIME = "pt_BR.UTF-8";
    };
  };

  # ============================================================================
  # DISPLAY & WINDOW MANAGEMENT
  # ============================================================================
  # services = {
  #   # X11 configuration
  #   xserver = {
  #     enable = true;

  #     # Window manager
  #     windowManager.i3.enable = true;

  #     # Keyboard layout
  #     xkb = {
  #       layout = "us";
  #       variant = "colemak_dh_wide";
  #       options = "caps:backspace, backspace:caps";
  #     };
  #   };

  #   # Display manager
  #   displayManager.defaultSession = "none+i3";

  #   # Input devices
  #   libinput = {
  #     mouse = {
  #       accelProfile = "flat";
  #       transformationMatrix = "1 0 0 0 2 0 0 0 1"; # 2x vertical speed
  #     };
  #   };
  # };

  # ============================================================================
  # SERVICES
  # ============================================================================
  services = {
    # Printing
    printing.enable = true;

    # Audio - PipeWire configuration
    pipewire = {
      enable = true;
      alsa = {
        enable = true;
        support32Bit = true;
      };
      pulse.enable = true;
      jack.enable = true;
    };

    # Disk management
    udisks2.enable = true;

    # Flatpak support
    flatpak.enable = true;
  };

  # ============================================================================
  # SECURITY
  # ============================================================================
  security.rtkit.enable = true;

  # ============================================================================
  # USER ACCOUNTS
  # ============================================================================
  users = {
    defaultUserShell = pkgs.zsh;
    users.felipe = {
      isNormalUser = true;
      description = "felipe";
      extraGroups = [
        "networkmanager"
        "wheel"
        "docker"
        "audio" # Required for microphone access
        "video" # Required for graphics access
      ];
      packages = with pkgs; [
        kdePackages.kate
        # thunderbird  # Disabled - uncomment to enable
      ];
    };
  };
  # ============================================================================
  # PROGRAMS
  # ============================================================================
  programs = {
    firefox.enable = true;
    zsh.enable = true;

    # GPG agent (uncomment if needed)
    # gnupg.agent = {
    #   enable = true;
    #   enableSSHSupport = true;
    # };

    # MTR network diagnostic tool (uncomment if needed)
    # mtr.enable = true;
  };

  # ============================================================================
  # NIX CONFIGURATION
  # ============================================================================
  nix = {
    # Enable flakes
    settings.experimental-features = [
      "nix-command"
      "flakes"
    ];
    settings.auto-optimise-store = true;  # New: Deduplicate store for faster builds

    # Set nixpkgs path
    nixPath = [ "nixpkgs = ${inputs.nixpkgs}" ];

    # Automatic garbage collection
    /*
      gc = {
        automatic = true;
        dates = "weekly";
        options = "--delete-older-than 30d";
      };
    */
  };

  programs.direnv = {
    enable = true;  # New: Auto-load project environments
    enableZshIntegration = true;
  };

  services.mpd = {
    enable = true;  # New: Music player daemon
    musicDirectory = "/home/felipe/Music";  # Adjust path as needed
  };

  # ============================================================================
  # SYSTEM PACKAGES
  # ============================================================================
  environment.systemPackages = with pkgs; [
    home-manager
    micro
    git
    vscode
    inputs.zen-browser.packages."${system}".default
    numix-icon-theme
    numix-solarized-gtk-theme

    # Portal packages for file dialogs to work in Wayland
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    xdg-desktop-portal-wlr
  ];

  nixpkgs = {
    config.allowUnfreePredicate = pkg: true;
    config.permittedInsecurePackages = [
      "googleearth-pro-7.3.6.10201"
      "xpdf-4.05"
      "python-2.7.18.12"
    ];
    overlays = [
      (final: prev: {
        nvchad = inputs.nix4nvchad.packages."${pkgs.system}".nvchad;
      })
    ];
  };

  # ============================================================================
  # Documentation & Help
  documentation.enable = false;

  # ============================================================================
  # FIREWALL & SSH
  # ============================================================================
  # SSH daemon (uncomment to enable)
  # services.openssh.enable = true;

  # Firewall configuration (uncomment and configure as needed)
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # networking.firewall.enable = false;

  # ============================================================================
  # SYSTEM STATE
  # ============================================================================
  # This determines the NixOS release for stateful data compatibility.
  # Only change after reading the documentation.
  system.stateVersion = "24.05";
}
