-- Auto-generated by iris. Do not edit; regenerated on every nh switch.
vim.g.colors_name = "iris"

local p = {
  bg        = "{bg}",
  bg_alt    = "{surface}",
  fg        = "{fg}",
  fg_dim    = "{dim}",
  accent    = "{accent}",
  red       = "{red}",
  green     = "{green}",
  yellow    = "{yellow}",

  keyword   = "{syntax_keyword}",
  string    = "{syntax_string}",
  func      = "{syntax_func}",
  type      = "{syntax_type}",
  const     = "{syntax_const}",
  comment   = "{syntax_comment}",
  param     = "{syntax_param}",
  operator  = "{syntax_operator}",
}

local hl = function(g, o) vim.api.nvim_set_hl(0, g, o) end

hl("Normal",       { fg = p.fg,  bg = "NONE" })
hl("NormalNC",     { fg = p.fg,  bg = "NONE" })
hl("NormalFloat",  { fg = p.fg,  bg = "NONE" })
hl("SignColumn",   { bg = "NONE" })
hl("EndOfBuffer",  { bg = "NONE" })
hl("LineNr",       { fg = p.fg_dim, bg = "NONE" })
hl("CursorLine",   { bg = p.bg_alt })
hl("CursorLineNr", { fg = p.accent, bold = true, bg = "NONE" })
hl("Visual",       { bg = p.keyword, fg = p.bg })
hl("StatusLine",   { fg = p.fg,  bg = p.bg_alt })
hl("Pmenu",        { fg = p.fg,  bg = p.bg_alt })
hl("PmenuSel",     { fg = p.bg,  bg = p.accent })
hl("WinSeparator", { fg = p.fg_dim, bg = "NONE" })
hl("FloatBorder",  { fg = p.fg_dim, bg = "NONE" })

hl("Comment",    { fg = p.comment, italic = true })
hl("Constant",   { fg = p.const })
hl("String",     { fg = p.string })
hl("Identifier", { fg = p.fg })
hl("Function",   { fg = p.func })
hl("Statement",  { fg = p.keyword, bold = true })
hl("Keyword",    { fg = p.keyword, bold = true })
hl("Type",       { fg = p.type })
hl("Special",    { fg = p.accent })

hl("DiagnosticError", { fg = p.red })
hl("DiagnosticWarn",  { fg = p.yellow })
hl("DiagnosticInfo",  { fg = p.green })
hl("DiagnosticHint",  { fg = p.fg_dim })

hl("@variable",         { link = "Identifier" })
hl("@function",         { link = "Function" })
hl("@function.builtin", { link = "Function" })
hl("@keyword",          { link = "Keyword" })
hl("@string",           { link = "String" })
hl("@comment",          { link = "Comment" })
hl("@type",             { link = "Type" })
hl("@punctuation",      { fg = p.fg_dim })

hl("@lsp.type.variable", { link = "Identifier" })
hl("@lsp.type.function", { link = "Function" })
hl("@lsp.type.class",    { link = "Type" })
